version: "3"

services:
  app:
    build: .
    restart: always
    hostname: hitcounter
    ports:
      - "5000:5000"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
