apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-service
  template:
    metadata:
      labels:
        run: hello-service
    spec:
      containers:
      - image: hello-service:v1
        imagePullPolicy: IfNotPresent
        name: hello-service
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
