apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  selector:
    run: hello-service
  ports:
  - nodePort: 30740
    port: 5000
    protocol: TCP
    targetPort: 5000
